//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Online
{


    public partial class Alta
    {

        /// <summary>
        /// Control lblNombre.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNombre;

        /// <summary>
        /// Control txtNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// Control rfvNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        /// <summary>
        /// Control lblPrecio.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrecio;

        /// <summary>
        /// Control txtPrecio.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;

        /// <summary>
        /// Control rfvPrecio.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPrecio;

        /// <summary>
        /// Control revPrecio.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPrecio;

        /// <summary>
        /// Control lblCategoria.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCategoria;

        /// <summary>
        /// Control ddlCategoria.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// Control rfvCategoria.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategoria;

        /// <summary>
        /// Control btnConfirmar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmar;

        /// <summary>
        /// Control lnkVolver.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkVolver;

        /// <summary>
        /// Control lblMensaje.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;
    }
}
