//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Online
{


    public partial class Baja
    {

        /// <summary>
        /// Control lnkVolver.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkVolver;

        /// <summary>
        /// Control lblMensaje.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        /// <summary>
        /// Control gvProductos.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProductos;
    }
}
